url: https://rundowntown.github.io
baseurl: /Gallop

######## Site settings ########
title: Gallop_1
email: contact@gallopstartup.com
description: "Gallop is an innovative startup building analytics and visualization tools to bridge policy and public sentiment."

######## Team names, titles and social links ########
people:
- name: Daniel Forcade
  pic: daniel
  position: Co-Founder & Data Architect
  social:
    - title: twitter
      url: https://twitter.com/danielforcade
    - title: github
      url: https://github.com/danielforcade

- name: Steven Wasserman
  pic: steven
  position: Co-Founder & Technical Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/stevenwasserman
    - title: github
      url: https://github.com/stevenwasserman

- name: Ryan Hopkins
  pic: ryan
  position: Machine Learning Engineer
  social:
    - title: github
      url: https://github.com/ryanhopkins
    - title: twitter
      url: https://twitter.com/ryanhopkins

- name: Hanna Bodnar
  pic: hanna
  position: Front-End Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/hannabodnar
    - title: instagram
      url: https://www.instagram.com/hannabodnar

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
